# See for details:
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow
    allow:
      - dependency-name: "com.h2database:h2"
      - dependency-name: "net.coobird:thumbnailator"
      - dependency-name: "org.apache.commons:commons-lang3"
      - dependency-name: "org.apache.commons:commons-text"
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "org.apache.maven.plugins:maven-clean-plugin"
      - dependency-name: "org.apache.maven.plugins:maven-enforcer-plugin"
      - dependency-name: "org.apache.maven.plugins:maven-resources-plugin"
      - dependency-name: "org.apache.maven.plugins:maven-war-plugin"
      - dependency-name: "org.jsoup:jsoup"
      - dependency-name: "org.liquibase:liquibase-core"
      - dependency-name: "org.projectlombok:lombok"
      - dependency-name: "org.hibernate.validator:hibernate-validator"
      - dependency-name: "org.webjars.npm:htmx.org"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
    ignore:
      - dependency-name: "org.hibernate.validator:hibernate-validator"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Novosibirsk"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message
    commit-message:
      prefix: "chore"
    assignees: [ "php-coder" ]
    labels: [ "kind/dependency-update" ]
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy
    rebase-strategy: "disabled"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Novosibirsk"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message
    commit-message:
      prefix: "ci"
    assignees: [ "php-coder" ]
    labels: [ "kind/dependency-update", "area/ci" ]
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy
    rebase-strategy: "disabled"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 1

  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
  # NOTE: only terraform >= 0.13 and <= 1.8.x is supported
  - package-ecosystem: "terraform"
    directory: "infra/terraform"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Novosibirsk"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message
    commit-message:
      prefix: "chore"
    assignees: [ "php-coder" ]
    labels: [ "kind/dependency-update" ]
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy
    rebase-strategy: "disabled"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 1
