# See for details:
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow
    allow:
      - dependency-name: "org.jsoup:jsoup"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Novosibirsk"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message
    commit-message:
      prefix: "chore"
    assignees: [ "php-coder" ]
    reviewers: [ "php-coder" ]
    labels: [ "kind/dependency-update" ]
