---

- name: Creating group
  group:
    name: mystamps
    state: present

- name: Create /data dir
  file:
      path: /data
      state: directory

- name: Creating user
  user:
    name: mystamps
    group: mystamps
    home: /data/mystamps
    createhome: yes
    comment: 'MyStamps'
    state: present

