--
-- Generated by maven: mvn -P dev clean compile hibernate3:hbm2ddl
--

    create table countries (
        id integer not null auto_increment,
        created_at datetime not null,
        name varchar(50) not null unique,
        primary key (id)
    ) ENGINE=InnoDB;

    create table suspicious_activities (
        id integer not null auto_increment,
        ip varchar(15) not null,
        occured_at datetime not null,
        page varchar(100) not null,
        referer_page varchar(255) not null,
        user_agent varchar(255) not null,
        type_id integer not null,
        user_id integer,
        primary key (id)
    ) ENGINE=InnoDB;

    create table suspicious_activities_types (
        id integer not null auto_increment,
        name varchar(100) not null unique,
        primary key (id)
    ) ENGINE=InnoDB;

    create table users (
        id integer not null auto_increment,
        activated_at datetime not null,
        email varchar(255) not null,
        hash varchar(40) not null,
        login varchar(15) not null unique,
        name varchar(100) not null,
        registered_at datetime not null,
        salt varchar(10) not null,
        primary key (id)
    ) ENGINE=InnoDB;

    create table users_activation (
        act_key varchar(10) not null,
        created_at datetime not null,
        email varchar(255) not null,
        primary key (act_key)
    ) ENGINE=InnoDB;

    alter table suspicious_activities 
        add index FK35F0CA0F8D3FBEA4 (user_id), 
        add constraint FK35F0CA0F8D3FBEA4 
        foreign key (user_id) 
        references users (id);

    alter table suspicious_activities 
        add index FK35F0CA0FC005E970 (type_id), 
        add constraint FK35F0CA0FC005E970 
        foreign key (type_id) 
        references suspicious_activities_types (id);
