# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"


  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = ENV["MYSTAMP_MEMORY"] || "2048"
    vb.name = "mystamps-devel"
  end

  config.vm.synced_folder ENV["MYSTAMPS_PATH"] || "../.", "/data/src/"
  config.vm.network "private_network", ip: '10.245.2.25'
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # before ansible provisioning, make sure we have ansible installed on the guest.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y ansible
  SHELL

  config.vm.provision :ansible do |ansible|
    ansible.limit = "mystamps-devel"
    ansible.verbose = ENV["ANSIBLE_VERBOSE"] || "vvvvv"
    ansible.playbook = "mystamps-base.yml"
    ansible.inventory_path = "inventory"
  end

end
