# Customize configuration from docker-compose.yml to run the application with
# the "prod" profile.
#
# In order to get the effective configuration, run
#   docker-compose -f docker-compose.yml -f prod.yml config
#
version: '3'

services:
  web:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # localhost -> db
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mystamps?logger=com.mysql.jdbc.log.Slf4JLogger&useSSL=false&logSlowQueries=true&slowQueryThresholdMillis=250&autoSlowLog=false&characterEncoding=UTF-8
      # override password from application-prod.properties to be the same as in db
      - SPRING_DATASOURCE_PASSWORD=secret
      # only for testing locally. See also: https://github.com/php-coder/mystamps/issues/670
      - SERVER_SERVLET_SESSION_COOKIE_SECURE=false
    volumes:
      - ./application-prod.properties:/data/mystamps/application-prod.properties:ro
      # to use a WAR file from filesystem and avoid to build an image every time
      #- ../../target/mystamps.war:/data/mystamps/mystamps.war:ro
    networks:
      - internal-network
    depends_on:
      - db
  db:
    # https://hub.docker.com/_/mysql
    # https://github.com/docker-library/mysql/blob/429047ac5e28d59d40a2ac84a189c9d25310f060/5.7/Dockerfile
    # NOTE: it's better to have the same as in .github/workflows/integration-tests-mysql.yml
    image: mysql:5.7.20
    command: --character-set-server=utf8
    environment:
      # NOTE: it's better to have credentials the same as in .github/workflows/integration-tests-mysql.yml
      # and src/main/resources/application-travis.properties
      # the generated root password will be printed to stdout (GENERATED ROOT PASSWORD: ...)
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=mystamps
      # FIXME: try to use a secret
      - MYSQL_PASSWORD=secret
      # the user specified above will be granted superuser access automatically
      - MYSQL_DATABASE=mystamps
    ports:
      - '3306:3306'
    # only for testing locally
    #volumes:
    #  - ./mysql_backup_mystamps.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz:ro
    networks:
      - internal-network

networks:
  internal-network:
