---

- name: Creating /data/backups
  file:
    path: /data/backups
    owner: mystamps
    group: mystamps
    mode: '0750'
    state: directory

- name: Granting access to the database to mystamps user
  template:
    src: my.cnf
    dest: /data/mystamps/.my.cnf
    force: yes
    backup: no
    owner: mystamps
    group: mystamps
    mode: '0600'

- name: Creating a cron task for doing database backups
  template:
    src: mystamps-backup-db
    dest: /etc/cron.d/mystamps-backup-db
    force: yes
    backup: no
    owner: root
    group: root
    mode: '0644'

- name: Removing old cron task
  file:
    path: /etc/cron.d/mystamps
    state: absent

- name: Installing duplicity
  apt:
    package: duplicity
    state: present

- name: Creating /etc/duplicity directory
  file:
    path: /etc/duplicity
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Downloading /etc/duplicity/cacert.pem
  command: curl https://curl.haxx.se/ca/cacert.pem -o cacert.pem
  args:
    chdir: /etc/duplicity
    creates: /etc/duplicity/cacert.pem
    warn: no

- name: Creating /data/bin directory
  file:
    path: /data/bin
    state: directory
    owner: root
    group: root
    mode: '0755'

# @todo #705 remote-backup.sh: find a way to protect duplicity against ps
- name: Creating a script for doing remote backup
  template:
    src: remote-backup.sh
    dest: /data/bin/remote-backup.sh
    force: yes
    backup: no
    owner: root
    group: root
    mode: '0700'

- name: Creating a cron task for backup to a remote host
  template:
    src: mystamps-backup-remote
    dest: /etc/cron.d/mystamps-backup-remote
    force: yes
    backup: no
    owner: root
    group: root
    mode: '0644'

