--
-- Auto-generated by Maven, based on values from src/main/resources/test/spring/test-data.properties
--

INSERT INTO series(id, quantity, perforated, country_id, created_at, created_by, updated_at, updated_by, category_id) VALUES
	(2, 1, 1, 2, NOW() + 1, 1, NOW(), 4, 1);

INSERT INTO series(id, quantity, perforated, country_id, created_at, created_by, updated_at, updated_by, category_id) VALUES
	(3, 1, 1, 2, NOW() + 2, 1, NOW(), 4, 1);
	
INSERT INTO series(id, quantity, perforated, country_id, created_at, created_by, updated_at, updated_by, category_id) VALUES
	(4, 1, 1, 2, NOW() + 3, 1, NOW(), 4, 1);

INSERT INTO series(id, quantity, perforated, country_id, created_at, created_by, updated_at, updated_by, category_id) VALUES
	(5, 1, 1, 2, NOW() + 4, 1, NOW(), 4, 1);

INSERT INTO series(id, quantity, perforated, country_id, created_at, created_by, updated_at, updated_by, category_id) VALUES
	(6, 1, 1, 4, NOW() + 5, 1, NOW(), 4, 1);
