---

- name: Creating /data/backups
  file:
    path: /data/backups
    owner: mystamps
    group: mystamps
    mode: '0755'
    state: directory

- name: Granting access to the database to mystamps user
  template:
    src: my.cnf
    dest: /data/mystamps/.my.cnf
    force: yes
    backup: no
    owner: mystamps
    group: mystamps
    mode: '0600'

- name: Creating a cron task for doing database backups
  copy:
    src: ../../src/main/config/cron/mystamps
    dest: /etc/cron.d/mystamps
    force: yes
    backup: no
    owner: root
    group: root
    mode: '0644'

