--
-- Auto-generated by Maven, based on values from src/env/test/spring/test-credentials.properties
--
INSERT INTO users(login, name, email, registered_at, activated_at, hash, salt)
VALUES (
	'@valid_user_login@',
	'@valid_user_name@',
	'coder@rock.home',
	NOW(),
	NOW(),
	'@valid_user_password_hash@',
	'@valid_user_password_salt@'
);
