--
-- Auto-generated by Maven, based on values from src/env/test/spring/test-credentials.properties
--
INSERT INTO users(login, name, email, registered_at, activated_at, hash, salt)
VALUES (
	'@valid_user_login@',
	'@valid_user_name@',
	'coder@rock.home',
	NOW(),
	NOW(),
	'@valid_user_password_hash@',
	'@valid_user_password_salt@'
);

INSERT INTO users_activation(act_key, email, created_at)
VALUES(
	'@not_activated_user_act_key@',
	'test@example.org',
	NOW()
);

INSERT INTO countries(name, created_at)
VALUES(
	'@valid_country_name@',
	NOW()
);
