@startuml

title Series import flow: stage 2 (download page)
hide footbox

participant ImportRequestCreatedEventListener
participant DownloaderService
participant SeriesImportService
participant EventPublisher

ImportRequestCreatedEventListener->DownloaderService: url
activate DownloaderService
DownloaderService->ImportRequestCreatedEventListener:
deactivate DownloaderService
alt
ImportRequestCreatedEventListener->SeriesImportService: content of downloaded page
activate SeriesImportService
SeriesImportService->SeriesImportService:
SeriesImportService->ImportRequestCreatedEventListener:
note right of SeriesImportService: Unprocessed -> DownloadingSucceeded
deactivate SeriesImportService
ImportRequestCreatedEventListener->EventPublisher: DownloadingSucceeded
else
ImportRequestCreatedEventListener->SeriesImportService:
activate SeriesImportService
SeriesImportService->ImportRequestCreatedEventListener:
note right of SeriesImportService: Unprocessed -> DownloadingFailed
deactivate SeriesImportService
end

@enduml