---
- hosts: all
  gather_facts: no
  remote_user: coder
  become: yes
  become_method: sudo
  vars:
    profile: 'prod'
  vars_files:
    - './vars/prod.yml'

  pre_tasks:

  - name: Removing nano
    apt:
      package: nano
      state: absent

  - name: Creating /data directory
    file:
      path: /data
      state: directory
      owner: root
      group: root
      mode: '0755'

  roles:
  - php-coder.oraclejdk
  - mystamps-user
  - role: mystamps-app
    tags: app
  - role: php-coder.nginx
    vars:
      remove_default_vhost: yes
      state: stopped
  - role: mystamps-nginx
    tags: ssl
  - role: mystamps-backup
    when: profile == 'prod'
    tags: backup
