--
-- Auto-generated by Maven, based on values from src/main/resources/test/spring/test-data.properties
--

-- Used below as country's owner
INSERT INTO users(id, login, name, registered_at, activated_at, hash, salt, email) VALUES
	(2, 'test0', '@valid_country_name@ Country Owner', NOW(), NOW(), '@valid_user_password_hash@', '@valid_user_password_salt@', 'test0@example.org');

-- Used only in WhenUserAddCountry
INSERT INTO countries(name, created_at, created_by, updated_at, updated_by) VALUES
	('@valid_country_name@', NOW(), 2, NOW(), 2);
