--
-- Auto-generated by Maven, based on values from src/main/resources/test/spring/test-data.properties
--

INSERT INTO zagorski_catalog(id, code) VALUES(1, '@existing_zagorski_number@');
INSERT INTO series_zagorski_catalog(series_id, zagorski_id) VALUES(1, 1);
