--
-- Auto-generated by Maven, based on values from src/main/resources/test/spring/test-data.properties
--

INSERT INTO solovyov_catalog(id, code) VALUES(1, '@existing_solovyov_number@');
INSERT INTO series_solovyov_catalog(series_id, solovyov_id) VALUES(1, 1);
