---
admin_email: coder
user_db_password: p@ssword
# Target urls should be in a format that is supported by duplicity(1):
# https://www.nongnu.org/duplicity/vers8/duplicity.1.html#sect7
uploads_target_url: file:///tmp/uploads
mysql_backups_target_url: file:///tmp/mysql-backups
# Passphrase for GPG to encrypt archives
gpg_passphrase:
