name: Integration Tests (H2)

on:
  push:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  # NOTE: actions/upload-artifact makes no use of permissions
  # See https://github.com/actions/upload-artifact/issues/197#issuecomment-832279436
  contents: read # for "git clone"

defaults:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
  run:
    # Enable fail-fast behavior using set -eo pipefail
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  run-integration-tests:
    name: Integration Tests
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations
        include:
          - java-version: '8'
            allow-failure: false
          - java-version: '11'
            allow-failure: true
          - java-version: '17'
            allow-failure: true
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
    continue-on-error: ${{ matrix.allow-failure }}
    steps:
      - name: Clone source code
        uses: actions/checkout@v4.2.0 # https://github.com/actions/checkout
        with:
          # Whether to configure the token or SSH key with the local git config. Default: true
          persist-credentials: false
      - name: Install JDK
        uses: actions/setup-java@v4.4.0 # https://github.com/actions/setup-java
        with:
          distribution: 'adopt'                    # https://github.com/actions/setup-java#supported-distributions
          java-version: ${{ matrix.java-version }} # https://github.com/actions/setup-java#supported-version-syntax
      - name: Restore existing cache
        uses: actions/cache@v4.0.2 # https://github.com/actions/cache
        with:
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#input-parameters-for-the-cache-action
          key: maven-repository-${{ hashFiles('pom.xml') }}
          path: ~/.m2/repository
          restore-keys: maven-repository-
      - name: Run integration tests
        run: ./src/main/scripts/execute-command.sh integration-tests
      - name: Save RobotFramework reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4.4.0 # https://github.com/actions/upload-artifact
        with:
          name: robotframework-reports
          path: target/robotframework-reports/
