name: Setup a server by Terraform

on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read # for "git clone"

defaults:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
  run:
    # Enable fail-fast behavior using set -eo pipefail
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  setup-server:
    name: Setup a server
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04
    steps:

      - name: Clone source code
        uses: actions/checkout@v3.5.2 # https://github.com/actions/checkout
        with:
          # Whether to configure the token or SSH key with the local git config. Default: true
          persist-credentials: false

      # https://github.com/tfutils/tfenv#manual
      - name: Install tfenv
        uses: actions/checkout@v3.5.2
        with:
          # https://github.com/actions/checkout#checkout-multiple-repos-nested
          repository: tfutils/tfenv
          path: tfenv
          ref: v3.0.0
          # Whether to configure the token or SSH key with the local git config. Default: true
          persist-credentials: false

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
      - name: Add tfenv directory to PATH
        run: echo "$GITHUB_WORKSPACE/tfenv/bin" >> $GITHUB_PATH

      # https://github.com/tfutils/tfenv#tfenv-install-version
      # https://github.com/tfutils/tfenv#tfenv-use-version
      - name: Install terraform
        working-directory: infra/terraform
        run: |
          tfenv install
          tfenv use

      - name: Show tools versions
        run: tfenv --version

      - name: Run terraform init
        working-directory: infra/terraform
        run: terraform init

      - name: Run terraform plan
        working-directory: infra/terraform
        run: terraform plan
