name: Quality Checks

on:
  push:

jobs:
  run-checkstyle:
    name: Run CheckStyle
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v3.1.0 # https://github.com/actions/checkout
        with:
          # Whether to configure the token or SSH key with the local git config. Default: true
          persist-credentials: false
      - name: Install JDK
        uses: actions/setup-java@v3.7.0 # https://github.com/actions/setup-java
        with:
          distribution: 'adopt' # https://github.com/actions/setup-java#supported-distributions
          java-version: '8'     # https://github.com/actions/setup-java#supported-version-syntax
          cache: 'maven'        # https://github.com/actions/setup-java#caching-packages-dependencies
      - name: Run CheckStyle
        run: ./src/main/scripts/execute-command.sh checkstyle
  run-pmd:
    name: Run PMD
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v3.1.0 # https://github.com/actions/checkout
        with:
          # Whether to configure the token or SSH key with the local git config. Default: true
          persist-credentials: false
      - name: Install JDK
        uses: actions/setup-java@v3.7.0 # https://github.com/actions/setup-java
        with:
          distribution: 'adopt' # https://github.com/actions/setup-java#supported-distributions
          java-version: '8'     # https://github.com/actions/setup-java#supported-version-syntax
          cache: 'maven'        # https://github.com/actions/setup-java#caching-packages-dependencies
      - name: Run PMD
        run: ./src/main/scripts/execute-command.sh pmd
  check-license:
    name: Check license in file headers
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v3.1.0 # https://github.com/actions/checkout
        with:
          # Whether to configure the token or SSH key with the local git config. Default: true
          persist-credentials: false
      - name: Install JDK
        uses: actions/setup-java@v3.7.0 # https://github.com/actions/setup-java
        with:
          distribution: 'adopt' # https://github.com/actions/setup-java#supported-distributions
          java-version: '8'     # https://github.com/actions/setup-java#supported-version-syntax
          cache: 'maven'        # https://github.com/actions/setup-java#caching-packages-dependencies
      - name: Check license header
        run: ./src/main/scripts/execute-command.sh check-license
